; PlatformIO Project Configuration File for JointGuard ESP32 Sensor Node
; Basic Ultrasonic Sensor (HC-SR04) Test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
